name: label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create label
        run: gh label create "$LABEL" --color "ededed" --force
        env:
          LABEL: chiellini
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_REPO: ${{github.repository}}

      - name: Add label to an issue
        run: gh issue edit "$NUMBER" --add-label "$LABEL"
        env:
          NUMBER: ${{ github.event.issue.number }}
          LABEL: help wanted
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_REPO: ${{github.repository}}